version: '3.3'

services:
    master:
        build: .
        ports:
            - 4040:4040
            - 8080:8080
        command: /spark/bin/spark-class org.apache.spark.deploy.master.Master --host 0.0.0.0

    worker:
        build: .
        depends_on:
            - master
        ports:
            - 8081-8089:8081
        command: /spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077 --host 0.0.0.0
