version: '3.3'

services:
  master:
    image: kazono/spark-docker:latest
    hostname: master
    command: ["master"]
    environment:
      MASTER: spark://master:7077
    ports:
      - 6066:6066
      - 7077:7077
      - 8480:8480

  worker:
    image: kazono/spark-docker:latest
    command: ["worker", "spark://master:7077"]
    depends_on:
      - master
    ports:
      - 8481-8489:8481
